stages:
  - test

test:
  stage: test
  image: python:3.13.5-slim
  before_script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
    - uv sync
  script: pytest test/**/test_*.py
  artifacts:
    paths:
      - results.xml
  allow_failure: false
