# ----------------------------
# Configuration file of the REI3 Tickets MCP Server.
# ----------------------------

[server]
# ----------------------------
# Transport configuration
# ----------------------------
#
# - stdio -> For when the MCP server and the *singular* calling MCP client are operated on the same machine.
# - http  -> For when the MCP server should handle multiple concurrent or remote clients.
#
# Further information:
# 'stdio': https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#stdio
# 'http' : https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#streamable-http
#
transport = http

# Only used when transport is set to 'http'.
host = 127.0.0.1
port = 4321

[rei3-tickets-api]
username   = admin
password   = admin
email      = tickets-mcp-server@mcp.local
profile    = 1
key_format = {key:06d}
base_url   = http://localhost:21918/