# ----------------------------
# Configuration file of the REI3 Tickets MCP Server.
# ----------------------------

[general]
host       = 127.0.0.1
port       = 54321

[mcp-server]
# ----------------------------
# Transport configuration
# ----------------------------
#
# - stdio -> For when the MCP server and the *singular* calling MCP client are operated on the same machine.
# - http  -> For when the MCP server should handle multiple concurrent or remote clients.
#
# Further information:
# 'stdio': https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#stdio
# 'http' : https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#streamable-http
#
transport  = http

[web-server]
# ----------------------------
# Enable setting
# ----------------------------
#
# Can only be used with http transport!
#
# Enables or disables the django based management web-application.
# This feature was primarily implemented for docker instances of the REI3 Tickets MCP server.
#
# Exposed endpoints:
#    - /mcp/   <- The REI3 Tickets MCP server endpoint. (Note: '/mcp' won't work, ensure you use '/mcp/'!)
#    - /       <- The django admin application.
#
# Default superuser account settings:
#    - username: admin
#    - password: admin
# -> Ensure to change these after the first login!
#
enable     = false

# ----------------------------
# Allowed Hosts
# ----------------------------
#
# The hosts that may access the django administration web-application.
#
# For production, specify the actual domain(s) or IP address(es) of the client(s) accessing the management web-application.
# (e.g.: allowed_hosts = example.com,www.example.com)
#
allowed_hosts = localhost,127.0.0.1

[rei3-tickets-api]
username   = admin
password   = admin
email      = tickets-mcp-server@mcp.local
profile    = 1
key_format = {key:06d}
base_url   = http://localhost:21918